# Generated by Django 6.0.4 on 2026-04-30 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('yoga', 'Yoga'), ('cardio', 'Cardio'), ('strength', 'Strength Training'), ('pilates', 'Pilates'), ('hiit', 'HIIT'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('boxing', 'Boxing')], default='cardio', max_length=50)),
                ('schedule', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('capacity', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='gym_classes', through='gym_app.Booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['schedule'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='gym_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.gymclass'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'gym_class')},
        ),
    ]
